# fly.toml app configuration file generated for empty-cherry-8518 on 2023-11-09T01:11:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-cherry-8518"
primary_region = "ams"

[build]

[env]
  PORT = "3000" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
